version: '3.3'

services:
  app:
    build:
      context: .
    logging:
      driver: json-file
      options:
        max-size: "200k"
    volumes:
       - ./notebooks:/opt/notebooks
       - .:/app
       - notebooks:/app/notebooks
    ports:
      - "3000:3000"
    tty: true

volumes:
  notebooks:
